app = "wevi-frontend"
primary_region = "sjc"

[build]

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[machine]
  memory = 512
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = 512