app = "wevi-backend"
primary_region = "sjc"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[machine]
  memory = 256
  cpu_kind = "shared"
  cpus = 1

[[vm]]
  size = "shared-cpu-1x"
  memory = 256